export { default as About } from "./About";
export { default as AddNewBldg } from "./AddNewBldg";
export { default as AddNewFloor } from "./AddNewFloor";
export { default as AddNewRoom } from "./AddNewRoom";
export { default as AddNewUser } from "./AddNewUser";
export { default as Feed } from "./Feed";
export { default as Home } from "./Home";
export { default as Login } from "./Login";
export { default as Profile } from "./Profile";
